name: pace_update
on:
  workflow_dispatch:
  schedule:
    - cron: "25 3 * * *" # https://crontab.guru/

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
      EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
      GITHUB_API_TOKEN: ${{ secrets.GT_API_TOKEN }}

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir Cython
          pip install -r requirements.txt
      - name: execute python script
        run: |
          python pace_update.py
      # - name: file_check
      #   run: ls -l -a
      # - name: commit files
      #   continue-on-error: true
      #   run: |
      #     today=$(date +"%Y-%m-%d")
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add -A
      #     git commit -m "Updated datasets ${today} UTC" -a
      #     git pull origin main
      # - name: push changes
      #   continue-on-error: true
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: main
